### ISSUE TITLE
Use coincurve instead of secp256k1 ?

### ISSUE THREAD

**Issue by Spl3en** [icon-project/icon-sdk-python#29]
`secp256k1` library is sadly difficult to compile on Windows, including the `secp256k1` Python package.
However, `coincurve` (https://github.com/ofek/coincurve) offers a crossplatform support and works similarly to secp256k1.

Wouldn't it be interesting to migrate the `secp256k1` package to `coincurve` in order to support the ICON SDK Python on Windows natively ?

**Comment by Spl3en** [comment]
Thanks for the answer ! 

Ah, I see. `coincurve` sounded like an easy way to replace `secp256k1-py`, but that's not so easy as I imagined.
Oh well, I hope `secp256k1` will eventually becomes easier to compile on Windows one day or another.

Cheers

**Comment by ofek** [comment]
@boyeon555 Hello there! Could you please tell me what exactly https://github.com/ludbb/secp256k1-py supports that https://github.com/ofek/coincurve doesn't? Every project on https://github.com/ofek/coincurve/blob/master/DOWNSTREAM.rst has switched and I've never heard a complaint about feature parity before.

When you say
> For example, loading key store file and converting to Private key object with user password is not supported

what do you mean? The library you use now also doesn't support that, so I'm quite confused.

@Spl3en Would you mind re-opening this for a bit?

**Comment by sink772** [comment]
@Spl3en I'm curious about your development environment on Windows. Are you using WSL? If so, AFAIK, you may install `iconsdk` without any trouble.  Otherwise, are you using Cygwin? Anyway, the information about the target environment on Windows is crucial for us to review the feasibility of the migration.

**Comment by Spl3en** [comment]
@sink772 Yes indeed, I am using WSL as a workaround for using iconsdk on Windows in the meantime.
Unfortunately, WSL is slow regarding network calls : https://github.com/Microsoft/WSL/issues/2864

For a library such as iconsdk that makes a lot of network calls, it makes the development quite painful on Windows.

**Comment by Kradenx** [comment]
So is this the module why I cannot build iconsdk on Windows? This seems to be copied from ethereum/bitcoin code too...

**Comment by Spl3en** [comment]
@Kradenx Yes, this module is hard to compile on Windows. It's definitely possible, but it's quite hard to configure pip in order to get the right build environment.

**Comment by ofek** [comment]
Any progress?

**Comment by Spl3en** [comment]
> Any progress?

Unfortunately, no progress so far.

**Comment by eunsoo-icon** [comment]
Applied in #48
