### ISSUE TITLE
Issue when installing iconsdk on Linux Ubuntu 18.04

### ISSUE THREAD

**Issue by Kradenx** [icon-project/icon-sdk-python#31]
Hello,
I wanted to work with the python iconsdk but cannot bring it to work, I tried to build it with pip, pip3 and pycharm. None of them seems to work and it seems to be a problem with secp256k1.
I cannot build those "wheels" for this module...
Someone has any ideas? 
My specs: Python 3.6.7, pip 19.0.3
I attached the error from pip:
[Error.zip](https://github.com/icon-project/icon-sdk-python/files/2974411/Error.zip)

**Comment by Spl3en** [comment]
It looks like an openssl version error. https://bitcoin.stackexchange.com/questions/50125/failing-to-build-bitcoin-core-v0-13-1-on-debian-stretch

**Comment by Kradenx** [comment]
Thanks for your fast response.

- It doesn't seem to be a good idea to use an old openssl version due to security... In this link they say it is also fixed in a new version. Anyway I tried to downgrade openssl to version on a virtual machine, but it doesn't work either. 

- Maybe you can tell me your specs where you can run the iconsdk without errors (E.g. which Linux distribution/version, python, and which other modules/programs)? If you have link to an offical Linux image for virtual machines would be nice too, so anyone can start programming without to worry about these dependencies.

**Comment by Kradenx** [comment]
So I found the problem, it was somehow connected with this secp256k1 module, which I could not build right at the first time. So if anyone has the same issues this worked for me:

pip install eth-keyfile
sudo pip install multipledispatch
sudo pip install request
sudo apt --fix-broken install
sudo apt install libsecp256k1-dev
sudo pip install secp256k1
sudo pip install iconsdk

**Comment by Spl3en** [comment]
Good to hear!

If anyone needs to check a clean install of iconsdk, I provide an updated VirtualBox image here : 
https://drive.google.com/open?id=1jFpC82-meZWPXukWhHAR7N0-3CNiPNkf
