### ISSUE TITLE
Issue happend when installing iconsdk

### ISSUE THREAD

**Issue by yulit0738** [icon-project/icon-sdk-python#32]
Hello all. I suffered from issue like below:
```sh
machine@DESKTOP:~$ pip install iconsdk
Collecting iconsdk
  Using cached https://files.pythonhosted.org/packages/90/88/b4659fb9849b78422f811cd95029d38af683f7c5d6fb42389c357cabc12e/iconsdk-1.0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9kyFTH/iconsdk/setup.py", line 22, in <module>
        with open(path.join('.', 'VERSION')) as version_file:
    IOError: [Errno 2] No such file or directory: './VERSION'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9kyFTH/iconsdk/
```

It seems to be setup.py module could not find appropriate VERSION file. 
Is there other ways to install python-SDK?

**PS : I'm using python 3.6.5 and Ubuntu18.04**

Many Thanks.

**Comment by Spl3en** [comment]
Indeed, there is no VERSION file in the released pip package, it should be fixed.

There are two workarounds I can see : 
- Either export an environment variable : `export VERSION=1.0.7` and try to do the pip install again
- Clone the current repository as it contains a VERSION file, and build it yourself using `build.sh`

**Comment by boyeon555** [comment]
I also got the same error message when installing iconsdk on python 2.x. 

Install it on python 3.x and it is recommended to use it on virtualenv environment as below:

```sh
$ virtualenv venv --python=python3
$ source venv/bin/activate
$ pip install iconsdk
```

**Comment by yulit0738** [comment]
It works when I try to install iconsdk on python3.

Many Thanks :)

**Comment by sulaaardit** [comment]
`ERROR: Command errored out with exit status 1: /Users/admin/Documents/icon-tutorial/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b8/9j5fnyr53kb1s78ypfxp2gxw0000gp/T/pip-install-o3etnveq/coincurve_736654d375e947cdab112ae9e3c2193d/setup.py'"'"'; __file__='"'"'/private/var/folders/b8/9j5fnyr53kb1s78ypfxp2gxw0000gp/T/pip-install-o3etnveq/coincurve_736654d375e947cdab112ae9e3c2193d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/b8/9j5fnyr53kb1s78ypfxp2gxw0000gp/T/pip-record-pzanla7g/install-record.txt --single-version-externally-managed --compile --install-headers /Users/admin/Documents/icon-tutorial/venv/include/site/python3.9/coincurve Check the logs for full command output.
`
` error: [Errno 2] No such file or directory: 'pkg-config'
  ----------------------------------------
  ERROR: Failed building wheel for coincurve`

I'm getting this error when trying to install iconsdk on virtualenv-python3. 

Any help will be greatly appreciated.
