### ISSUE TITLE
ERROR: While trying to install Iconsdk.

### ISSUE THREAD

**Issue by sulaaardit** [icon-project/icon-sdk-python#62]
`ERROR: Command errored out with exit status 1: /Users/admin/Documents/icon-tutorial/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b8/9j5fnyr53kb1s78ypfxp2gxw0000gp/T/pip-install-o3etnveq/coincurve_736654d375e947cdab112ae9e3c2193d/setup.py'"'"'; __file__='"'"'/private/var/folders/b8/9j5fnyr53kb1s78ypfxp2gxw0000gp/T/pip-install-o3etnveq/coincurve_736654d375e947cdab112ae9e3c2193d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/b8/9j5fnyr53kb1s78ypfxp2gxw0000gp/T/pip-record-pzanla7g/install-record.txt --single-version-externally-managed --compile --install-headers /Users/admin/Documents/icon-tutorial/venv/include/site/python3.9/coincurve Check the logs for full command output.
`

>  error: [Errno 2] No such file or directory: 'pkg-config'

  ----------------------------------------

>   ERROR: Failed building wheel for coincurve

I'm getting this error when trying to install iconsdk on virtualenv-python3. 

Any help will be greatly appreciated.

**Comment by eunsoo-icon** [comment]
I think you user MacOS.

You can install pkg-config with following command

```
brew install pkg-config
```

**Comment by sulaaardit** [comment]
Thank you that did the trick :)
