### ISSUE TITLE
Allow `term` to be passed while depositing for virtual step

### ISSUE THREAD

**Issue by ajaya-man** [icon-project/icon-sdk-python#63]
Currently the SDK doesn't take the `term` params to supply the number of months we want to deposit fee. 

In the integration test we can see that the [iconservice code](https://github.com/icon-project/icon-service/blob/master/tests/integrate_test/test_integrate_base.py#L920) has been tested to take the `term` parameter while depositing the ICX for virtual step but not used in SDK.

Can we get the implementation of `term` in SDK so that the ICX can be deposited for longer term and maximum utilization of virtual step can be done.

**Comment by sink772** [comment]
Hello @ajaya-man,

Below is the official spec of `deposit` dataType, and we don't support the `term` param in the spec.
https://github.com/icon-project/icon-rpc-server/blob/master/docs/icon-json-rpc-v3.md#datatype--deposit

Whatever the test code has written, `term` is not a valid parameter for the `deposit` officially and only `FIXED_TERM` semantic is used as of now. From my understanding, there is no concrete plan of supporting variable term.
