### ISSUE TITLE
import iconsdk doesnt work 

### ISSUE THREAD

**Issue by paulrouge** [icon-project/icon-sdk-python#85]
When importing iconsdk I get an error:

```
/usr/local/lib/python3.8/dist-packages/eth_utils/network.py:44: UserWarning: Network 345 
with name 'Yooldo Verse Mainnet' does not have a valid ChainId. eth-typing should be updated 
with the latest networks.
 warnings.warn(
/usr/local/lib/python3.8/dist-packages/eth_utils/network.py:44: UserWarning: 
Network 12611 with name 'Astar zkEVM' does not have a valid ChainId. eth-typing should 
be updated with the latest networks.
  warnings.warn(
```

Im using Python 3.8.10 on a Linux machine.

**Comment by eunsoo-icon** [comment]
The error caused by eth libraries not by iconsdk.
 
What version of eth libraries do you use?

I have no problem with python 3.9.17 and following eth libraries
```shell
$ pip list                                                              *[master]
Package            Version
------------------ --------
...
eth-hash           0.7.0
eth-keyfile        0.6.1
eth-keys           0.4.0
eth-typing         3.5.2
eth-utils          2.3.1
...
```

**Comment by sink772** [comment]
https://github.com/ethereum/eth-utils/pull/276

**Comment by paulrouge** [comment]
Thank you,

I'm not to familiar with Python. But shouldnt `pip install iconsdk` just work?

I get the error when importing `iconsdk`  and I'm not importing anything else.

**Comment by sink772** [comment]
Much like JavaScript development environments, Python also tends to have dependency hell.

It seems you've installed `iconsdk` in global context and using it without any sandboxed dependency env.
It looks like `eth-utils` has been upgraded later while performing your other tasks.

Usually we use `virtualenv` to separate the dependencies from other Python projects.

You need to upgrade `eth-utils` by yourself if you'd like to keep using the global context dev env.

**Comment by paulrouge** [comment]
Thank you!
